# Generated by Django 5.2.8 on 2025-12-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto referencial del espacio', null=True, upload_to='espacios/'),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='ubicacion',
            field=models.CharField(max_length=200),
        ),
    ]
