# Generated by Django 5.2.8 on 2025-12-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_espacio_imagen_alter_espacio_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='codigo',
            field=models.CharField(default='SIN-COD', max_length=50, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Total Físico'),
        ),
    ]
