# Generated by Django 5.2.8 on 2025-12-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SOLICITANTE', 'Solicitante')], default='SOLICITANTE', max_length=20),
        ),
    ]
