# Generated by Django 5.2.8 on 2025-12-11 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_area_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_directos', to='core.area', verbose_name='Área (Facultad)'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_solicitante',
            field=models.CharField(choices=[('DOCENTE', 'Docente'), ('COORDINADOR', 'Coordinador'), ('AMBOS', 'Docente y Coordinador')], default='DOCENTE', max_length=20, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SOLICITANTE', 'Solicitante')], default='SOLICITANTE', max_length=20, verbose_name='Rol de Sistema'),
        ),
    ]
