# Generated by Django 5.2.8 on 2025-12-18 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_area_user_tipo_solicitante_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.carrera', verbose_name='Carrera'),
        ),
    ]
