# Generated by Django 5.2.8 on 2025-12-01 04:08

import django.core.validators
import django.db.models.deletion
import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='Solo archivos PDF o Excel. Máx 5MB.', null=True, upload_to='reservas_adjuntos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xls', 'xlsx']), reservas.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'En Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservarecurso',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_asociados', to='reservas.reserva'),
        ),
    ]
