# Generated by Django 5.2.8 on 2025-12-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_archivo_adjunto_alter_reserva_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Razón por la cual se canceló la reserva', null=True),
        ),
    ]
