# Generated by Django 5.2.8 on 2025-12-11 05:54

import django.core.validators
import django.db.models.deletion
import reservas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_recurso_codigo_alter_recurso_stock'),
        ('reservas', '0003_reserva_motivo_cancelacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha', '-hora_inicio'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='Solo archivos PDF o Excel. Máx 5MB.', null=True, upload_to='reservas_adjuntos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xls', 'xlsx']), reservas.models.validate_file_size], verbose_name='Documento Adjunto'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.espacio', verbose_name='Espacio Solicitado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'En Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado Actual'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(verbose_name='Fecha Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(verbose_name='Hora Término'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='motivo',
            field=models.TextField(verbose_name='Motivo / Actividad'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Razón por la cual se canceló la reserva', null=True, verbose_name='Motivo Rechazo/Cancelación'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.CreateModel(
            name='RecursoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.recurso')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_asociados', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Recurso en Reserva',
                'verbose_name_plural': 'Recursos en Reservas',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='recursos',
            field=models.ManyToManyField(blank=True, related_name='reservas_involucradas', through='reservas.RecursoReserva', to='inventario.recurso'),
        ),
        migrations.DeleteModel(
            name='ReservaRecurso',
        ),
    ]
